version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./Sorting.Console/Sorting.Console.csproj
after_build:
artifacts:
 - path: '\src\bin\Debug\netcoreapp2.1\publish'
   name: Sorting
   type: Zip
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test
on_finish :
deploy: off