version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./Sorting.Console/Sorting.Console.csproj
after_build:
artifacts:
 - path: './Sorting.Console/bin/Debug/netcoreapp2.1/publish'
   name: Sorting
   type: Zip
clone_depth: 1
test_script:
  - cmd: dotnet restore ./Sorting.Console.Tests/Sorting.Console.Tests.csproj --verbosity m
  - cmd: dotnet test ./Sorting.Console.Tests/
  - cmd: dotnet restore ./Sorting.Domain.Tests/Sorting.Domain.Tests.csproj --verbosity m
  - cmd: dotnet test ./Sorting.Domain.Tests/
  - cmd: dotnet restore ./Sorting.Infrastructure.Tests/Sorting.Infrastructure.Tests.csproj --verbosity m
  - cmd: dotnet test ./Sorting.Infrastructure.Tests/
on_finish :
deploy: off